#1_NB_Classifier_Weather

Aim: Implement Naive Bayes classifier : Weather Example

###Import Libraries

In [37]:
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB, MultinomialNB

###Prepare Dataset

In [38]:
weather = ['Sunny', 'Sunny', 'Overcast', 'Rainy', 'Rainy','Rainy', 'Overcast',
           'Sunny', 'Sunny', 'Rainy', 'Sunny', 'Overcast', 'Overcast', 'Rainy']

temp = ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild',
        'Cool','Mild','Mild','Mild','Hot','Mild']

play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes',
      'Yes','Yes','Yes','Yes','No']

###Digitize the data set using encoding

In [39]:
le = preprocessing.LabelEncoder()

weather_encoded = le.fit_transform(weather)
weather_encoded

array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1])

In [40]:
temp_encoded = le.fit_transform(temp)

temp_encoded

array([1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2])

In [41]:
label = le.fit_transform(play)
label

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

####Manual Calculations

In [42]:
features=tuple(zip(weather,temp,play))
features

(('Sunny', 'Hot', 'No'),
 ('Sunny', 'Hot', 'No'),
 ('Overcast', 'Hot', 'Yes'),
 ('Rainy', 'Mild', 'Yes'),
 ('Rainy', 'Cool', 'Yes'),
 ('Rainy', 'Cool', 'No'),
 ('Overcast', 'Cool', 'Yes'),
 ('Sunny', 'Mild', 'No'),
 ('Sunny', 'Cool', 'Yes'),
 ('Rainy', 'Mild', 'Yes'),
 ('Sunny', 'Mild', 'Yes'),
 ('Overcast', 'Mild', 'Yes'),
 ('Overcast', 'Hot', 'Yes'),
 ('Rainy', 'Mild', 'No'))

In [43]:
totalCases = len(features)
# Probablity of Play 
pY = 0
# Probablity of Not Play 
pN = 0

# Probablity of Yes and Sunny
p_S_Y = 0;
# Probablity of Yes and OverCast
p_O_Y = 0;
# Probablity of Yes and Rainy
p_R_Y = 0;


# Probablity of Yes and Hot
p_H_Y = 0;
# Probablity of Yes and Mild
p_M_Y = 0;
# Probablity of Yes and Cool
p_C_Y = 0;

# Probablity of No and Sunny
p_S_N = 0;
# Probablity of No and OverCast
p_O_N = 0;
# Probablity of No and Rainy
p_R_N = 0;


# Probablity of No and Hot
p_H_N = 0;
# Probablity of No and Mild
p_M_N = 0;
# Probablity of No and Cool
p_C_N = 0;



for index, item in enumerate(features):
    
    if item[2] == 'Yes':
      if item[0] == 'Sunny':
        p_S_Y+=1
      elif item[0] == 'Overcast':
        p_O_Y+=1
      else:
        p_R_Y+=1

      if item[1] == 'Hot':
        p_H_Y+=1
      elif item[1] == 'Mild':
        p_M_Y+=1
      else:
        p_C_Y+=1

      pY+=1

    if item[2] == 'No':
      if item[0] == 'Sunny':
        p_S_N+=1
      elif item[0] == 'Overcast':
        p_O_N+=1
      else:
        p_R_N+=1

      if item[1] == 'Hot':
        p_H_N+=1
      elif item[1] == 'Mild':
        p_M_N+=1
      else:
        p_C_N+=1


      pN+=1

p_S_Y /= pY
p_O_Y /= pY
p_R_Y /= pY

p_H_Y /= pY
p_M_Y /= pY
p_C_Y /= pY
pY = pY/totalCases

p_S_N /= pN
p_O_N /= pN
p_R_N /= pN

p_H_N /= pN
p_M_N /= pN
p_C_N /= pN
pN /= totalCases

# probablity of play when weather is Sunny and temp is Mild
p_S_M =(p_S_Y* p_M_Y * pY) + (p_S_N * p_M_N * pN)
p_Y_SM = p_S_Y * p_M_Y * pY / p_S_M


# probablity of play when weather is Overcast and temp is Mild
p_O_M =(p_O_Y* p_M_Y * pY) + (p_O_N * p_M_N * pN)
p_Y_OM = p_O_Y * p_M_Y * pY / p_O_M


# probablity of play when weather is Sunny and temp is Hot
p_S_H = (p_S_Y * p_H_Y * pY) + (p_S_N * p_H_N * pN)
p_Y_SH = p_S_Y * p_H_Y * pY / p_S_H

p_Y_SM

0.425531914893617

###Merge different features to prepare dataset

In [44]:
features_encoded=tuple(zip(weather_encoded,temp_encoded))
features_encoded

((2, 1),
 (2, 1),
 (0, 1),
 (1, 2),
 (1, 0),
 (1, 0),
 (0, 0),
 (2, 2),
 (2, 0),
 (1, 2),
 (2, 2),
 (0, 2),
 (0, 1),
 (1, 2))

###Train ’Naive Bayes Classifier’

In [45]:
model = MultinomialNB()

model.fit(features_encoded,label)

MultinomialNB()

###Predict Output for new data

In [46]:
predicted_Overcast_Mild = model.predict([[0,2]])
predicted_Overcast_Mild

array([1])

In [47]:
predicted_Overcast_Hot = model.predict([[0,1]])
predicted_Overcast_Hot

array([1])

In [48]:
predicted_Sunny_Mild = model.predict([[2,2]])
predicted_Sunny_Mild

array([1])

#2_NB_Classifier_Iris_2Classes



In [27]:
#Import scikit-learn dataset library
import numpy as np
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

#Load dataset
iris = datasets.load_iris()

In [28]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [29]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [30]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [31]:
newdata = iris.data[50:,:]
newtarget = iris.target[50:]

In [32]:
from sklearn.model_selection import train_test_split

data_train, data_test, target_train, target_test = train_test_split(newdata,newtarget,test_size = .30, random_state=110)


In [33]:
import numpy as np

gnb = GaussianNB()

gnb.fit(data_train, target_train)

target_pred = gnb.predict(data_test)

In [34]:
from sklearn import metrics

metrics.accuracy_score(target_test, target_pred)

0.9666666666666667

In [35]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[14,  0],
       [ 1, 15]])

In [36]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred)
recall = recall_score(target_test, target_pred)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: 0.9333333333333333
recall: 1.0


#Exercise:

####Task1

In [11]:
import numpy as np
import pandas as pd
dataset=pd.read_csv('/content/Dataset3.csv');
print("Describe\n",dataset);
print("\nDescription\n",dataset.describe())

Describe
    Outlook Temp Wind  Humidity  Class
0        R    H    F         1      0
1        R    H    T         2      0
2        O    H    F         1      1
3        R    M    F         1      1
4        S    C    F         1      1
5        O    C    T         0      0
6        O    C    T         1      1
7        R    M    F         1      0
8        O    C    F         0      1
9        S    M    F         2      1
10       R    C    T         2      0
11       O    M    T         0      1
12       O    H    F         1      1
13       S    M    T         1      0

Description
         Humidity      Class
count  14.000000  14.000000
mean    1.000000   0.571429
std     0.679366   0.513553
min     0.000000   0.000000
25%     1.000000   0.000000
50%     1.000000   1.000000
75%     1.000000   1.000000
max     2.000000   1.000000


In [12]:
print("Shape of dataset",dataset.shape)

Shape of dataset (14, 5)


In [13]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Outlook   14 non-null     object
 1   Temp      14 non-null     object
 2   Wind      14 non-null     object
 3   Humidity  14 non-null     int64 
 4   Class     14 non-null     int64 
dtypes: int64(2), object(3)
memory usage: 688.0+ bytes


In [14]:
start='\033[1m' #make text after start keyword bold 
end='\033[0m' #make text back to normal
print(start+"Unique outlook values"+end,dataset["Outlook"].unique())
print(start+"\nUnique temperature vlaues"+end,dataset["Temp"].unique())
print(start+"\nUnique Wind values"+end,dataset["Wind"].unique())
print(start+"\nUnique Humidity values"+end,dataset["Humidity"].unique())
print(start+"\nUnique Class values"+end,dataset["Class"].unique())

Unique outlook values ['R' 'O' 'S']

Unique temperature vlaues ['H' 'M' 'C']

Unique Wind values ['F' 'T']

Unique Humidity values [1 2 0]

Unique Class values [0 1]


In [15]:
print("Each column datatype",dataset.dtypes)

Each column datatype Outlook     object
Temp        object
Wind        object
Humidity     int64
Class        int64
dtype: object


In [16]:
#using OneHotEncoding
from sklearn import preprocessing
ohe=preprocessing.OneHotEncoder()

In [17]:
ohe_data=pd.get_dummies(dataset,columns=['Outlook','Temp','Wind'])
print("Dummy after onehotencoding:\n",ohe_data)

Dummy after onehotencoding:
     Humidity  Class  Outlook_O  Outlook_R  ...  Temp_H  Temp_M  Wind_F  Wind_T
0          1      0          0          1  ...       1       0       1       0
1          2      0          0          1  ...       1       0       0       1
2          1      1          1          0  ...       1       0       1       0
3          1      1          0          1  ...       0       1       1       0
4          1      1          0          0  ...       0       0       1       0
5          0      0          1          0  ...       0       0       0       1
6          1      1          1          0  ...       0       0       0       1
7          1      0          0          1  ...       0       1       1       0
8          0      1          1          0  ...       0       0       1       0
9          2      1          0          0  ...       0       1       1       0
10         2      0          0          1  ...       0       0       0       1
11         0      1    

In [18]:
label=dataset.Class
print("Label\n",label)
non_label=ohe_data[['Humidity','Outlook_O','Outlook_R','Outlook_S','Temp_C','Temp_H','Temp_M','Wind_F','Wind_T']]
print("Non label\n",non_label)

Label
 0     0
1     0
2     1
3     1
4     1
5     0
6     1
7     0
8     1
9     1
10    0
11    1
12    1
13    0
Name: Class, dtype: int64
Non label
     Humidity  Outlook_O  Outlook_R  Outlook_S  ...  Temp_H  Temp_M  Wind_F  Wind_T
0          1          0          1          0  ...       1       0       1       0
1          2          0          1          0  ...       1       0       0       1
2          1          1          0          0  ...       1       0       1       0
3          1          0          1          0  ...       0       1       1       0
4          1          0          0          1  ...       0       0       1       0
5          0          1          0          0  ...       0       0       0       1
6          1          1          0          0  ...       0       0       0       1
7          1          0          1          0  ...       0       1       1       0
8          0          1          0          0  ...       0       0       1       0
9          2  

In [19]:
from sklearn.model_selection import train_test_split
data_train,data_test,target_train,target_test=train_test_split(non_label,label,train_size=0.85,random_state=110)

In [20]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
#train model based on training datasets
gnb.fit(data_train,target_train)

GaussianNB()

In [21]:
#prediction for test dataset
tar_pred=gnb.predict(data_test)
print("Prediction:",tar_pred)

Prediction: [0 0 0]


In [22]:
#accuracy
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(target_test,tar_pred))

Accuracy: 0.0


In [23]:
#confusion martix
from sklearn.metrics import confusion_matrix
print("Confusion matrix:")
confusion_matrix(target_test,tar_pred)

Confusion matrix:


array([[0, 0],
       [3, 0]])

In [24]:
from sklearn.metrics import precision_score,recall_score
precision=precision_score(target_test,tar_pred)
recall=recall_score(target_test,tar_pred)
print("Precision:",precision)
print("\nRecall:",recall)

Precision: 0.0

Recall: 0.0


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


(1) What will be the value of Play, if Outlook is ’Rainy’, Temperature is ’Mild’, Humidity =’Normal’, and Wind = ’False’?

In [25]:
q1=[1,0,1,0,0,0,1,1,0] #1 for humidity normal
v1=pd.DataFrame([q1],columns=["Humidity","Outlook_O","Outlook_R","Outlook_S","Temp_C","Temp_H","Temp_M","Wind_F","Wind_T"])
prediction1=gnb.predict(v1)
print("Prediction for (1) is:",prediction1)

Prediction for (1) is: [1]


(2) What will be the value of Play, if Outlook is ’Sunny’, Temeprature is ’Cool’, Humidity =’High’,
and Wind = ’True’?

In [26]:
q2=[2,0,0,1,1,0,0,0,1] #2 for humidity high
v2=pd.DataFrame([q2],columns=["Humidity","Outlook_O","Outlook_R","Outlook_S","Temp_C","Temp_H","Temp_M","Wind_F","Wind_T"])
prediction2=gnb.predict(v2)
print("Prediction for (2) is:",prediction2)

Prediction for (2) is: [0]


####Task2

In [1]:
from sklearn.datasets import load_wine
import numpy as np
from sklearn.naive_bayes import GaussianNB
data=load_wine()

In [2]:
print("Features:",data.feature_names)
print("\nLabels:",data.target_names);
print("\nData shape:",data.data.shape)
print("\n Target shape:",data.target.shape)
print("\nDate type:",type(data.data))

Features: ['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']

Labels: ['class_0' 'class_1' 'class_2']

Data shape: (178, 13)

 Target shape: (178,)

Date type: <class 'numpy.ndarray'>


In [3]:
bold="\033[1m"
end="\033[0m"
newdata=data.data[40:,:]
newtarget=data.target[40:]
print(bold+"Newdata:\n"+end,newdata)
print(bold+"\nNew target:\n"+end,newtarget)

Newdata:
 [[1.356e+01 1.710e+00 2.310e+00 ... 9.500e-01 3.380e+00 7.950e+02]
 [1.341e+01 3.840e+00 2.120e+00 ... 9.100e-01 3.000e+00 1.035e+03]
 [1.388e+01 1.890e+00 2.590e+00 ... 8.800e-01 3.560e+00 1.095e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]

New target:
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [4]:
print("New data shape:",newdata.shape)
print("New target shape:",newtarget.shape)

New data shape: (138, 13)
New target shape: (138,)


In [5]:
from sklearn.model_selection import train_test_split
data_train,data_test,target_train,target_test=train_test_split(newdata,newtarget,train_size=0.66,random_state=110)

In [6]:
import numpy as np
gnb=GaussianNB()
#train model using training sets
gnb.fit(data_train,target_train)
target_pred=gnb.predict(data_test)

In [7]:
#Accuracy
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(target_test,target_pred))

Accuracy: 1.0


In [8]:
#confusion matrix
from sklearn.metrics import confusion_matrix
print("Confusion matrix:")
confusion_matrix(target_test,target_pred)

Confusion matrix:


array([[ 5,  0,  0],
       [ 0, 25,  0],
       [ 0,  0, 17]])

In [9]:
#precision and recall
from sklearn.metrics import precision_score,recall_score
precision=precision_score(target_test,target_pred,average=None)
recall=recall_score(target_test,target_pred,average=None)
print("Precision:",precision)
print("\nRecall:",recall)

Precision: [1. 1. 1.]

Recall: [1. 1. 1.]
